# Generated by Django 5.1.6 on 2026-03-12 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroFinanceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='DATA')),
                ('mes', models.CharField(max_length=20, verbose_name='Mês')),
                ('periodo', models.CharField(max_length=50, verbose_name='Período')),
                ('arquivo', models.CharField(max_length=255, verbose_name='ARQUIVO')),
                ('rf_sub', models.CharField(max_length=100, verbose_name='RF-SUB')),
                ('unidade_coordenacao', models.CharField(max_length=255, verbose_name='Unidade/Coordenação')),
                ('grupos', models.CharField(max_length=255, verbose_name='Grupos')),
                ('despesa_gerencial', models.CharField(max_length=255, verbose_name='Despesa Gerencial')),
                ('iniciativa', models.CharField(max_length=255, verbose_name='Iniciativa')),
                ('gnd', models.CharField(max_length=100, verbose_name='GND')),
                ('tipo_despesa', models.CharField(max_length=255, verbose_name='Tipo de Despesa')),
                ('ro_1', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='RO-1')),
                ('lme_1', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='LME-1')),
                ('po', models.CharField(max_length=100, verbose_name='PO')),
                ('acao', models.CharField(max_length=255, verbose_name='AÇÃO')),
                ('po_gnd', models.CharField(max_length=100, verbose_name='PO+GND')),
            ],
            options={
                'verbose_name': 'Registro Financeiro',
                'verbose_name_plural': 'Registros Financeiros',
            },
        ),
    ]
