# Generated by Django 5.1.6 on 2026-03-13 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geofi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrofinanceiro',
            name='linha_id',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='registrofinanceiro',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
