# Generated by Django 5.1.6 on 2026-03-17 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geofi', '0002_registrofinanceiro_linha_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrofinanceiro',
            name='data',
            field=models.DateField(blank=True, null=True, verbose_name='DATA'),
        ),
    ]
